CREATE TABLE device
(
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    serial text
);

CREATE TABLE client
(
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    vk_id INTEGER,
    device_id INTEGER references device(id),
    PRIMARY KEY (id)
);

-- ALTER TABLE user
-- ADD PRIMARY KEY (id);



-- ALTER TABLE journal
-- ADD PRIMARY KEY (id);

CREATE TABLE data
(
    id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time TIMESTAMP,
    voltage INTEGER,
    device_id INTEGER REFERENCES device(id)
);


-- ALTER TABLE mark
-- ADD PRIMARY KEY (id);

-- ALTER TABLE journal
-- ADD CONSTRAINT R_8 FOREIGN KEY (journal_id) REFERENCES student (id);
--
-- ALTER TABLE journal
-- ADD CONSTRAINT R_11 FOREIGN KEY (mark_id) REFERENCES mark (id);
--
-- ALTER TABLE journal
-- ADD CONSTRAINT R_12 FOREIGN KEY (study_plan_id) REFERENCES study_plan (id);
--
-- ALTER TABLE student
-- ADD CONSTRAINT R_7 FOREIGN KEY (study_group_id) REFERENCES study_group (id);
--
-- ALTER TABLE study_plan
-- ADD CONSTRAINT R_9 FOREIGN KEY (subject_id) REFERENCES subject (id);
--
-- ALTER TABLE study_plan
-- ADD CONSTRAINT R_10 FOREIGN KEY (exam_type_id) REFERENCES exam_type (id);
--
-- INSERT INTO subject (id, name, short_name) VALUES
-- (1, 'Проектирование информационных систем', 'ПрИС'),
-- (2, 'Системы искусственного интеллекта', 'СИИ'),
-- (3, 'Программная инженерия', 'ПИ'),
-- (4, 'Национальная система информационной безопасности', 'НСИБ'),
-- (5, 'Системный анализ', 'СисАнал'),
-- (6, 'Распределенные базы данных', 'РБД'),
-- (7, 'Системное программное обеспечение', 'СПО');
--
-- INSERT INTO exam_type (id, type) VALUES
-- (1, 'Экзамен'),
-- (2, 'Зачет'),
-- (3, 'Зачет с оценкой'),
-- (4, 'Курсовая');
--
-- INSERT INTO study_plan (id, subject_id, exam_type_id) VALUES
-- (1, 1, 1),
-- (2, 1, 4),
-- (3, 2, 1),
-- (4, 3, 1),
-- (5, 4, 2),
-- (6, 5, 1),
-- (7, 6, 2),
-- (8, 7, 1);
--
-- INSERT INTO mark (id, name, value) VALUES
-- (1, 'Отлично', 5),
-- (2, 'Хорошо', 4),
-- (3, 'Удовлетворительно', 3),
-- (4, 'Неудовлетворительно', 2),
-- (5, 'Зачет', 'з'),
-- (6, 'Незачет', 'н'),
-- (7, 'Неявка', '');